alias sklist_2016a="cd ${SKFlat_WD}/data/${SKFlatV}/2016preVFP/Sample"
alias sklist_2016b="cd ${SKFlat_WD}/data/${SKFlatV}/2016postVFP/Sample"
alias sklist_2017="cd ${SKFlat_WD}/data/${SKFlatV}/2017/Sample"
alias sklist_2018="cd ${SKFlat_WD}/data/${SKFlatV}/2018/Sample"
alias skpu_2016a="cd ${SKFlat_WD}/data/${SKFlatV}/2016preVFP/PileUp"
alias skpu_2016b="cd ${SKFlat_WD}/data/${SKFlatV}/2016postVFP/PileUp"
alias skpu_2017="cd ${SKFlat_WD}/data/${SKFlatV}/2017/PileUp"
alias skpu_2018="cd ${SKFlat_WD}/data/${SKFlatV}/2018/PileUp"
alias skelid_2016a="cd ${SKFlat_WD}/data/${SKFlatV}/2016preVFP/ID/Electron"
alias skelid_2016b="cd ${SKFlat_WD}/data/${SKFlatV}/2016postVFP/ID/Electron"
alias skelid_2017="cd ${SKFlat_WD}/data/${SKFlatV}/2017/ID/Electron"
alias skelid_2018="cd ${SKFlat_WD}/data/${SKFlatV}/2018/ID/Electron"
alias skmuid_2016a="cd ${SKFlat_WD}/data/${SKFlatV}/2016preVFP/ID/Muon"
alias skmuid_2016b="cd ${SKFlat_WD}/data/${SKFlatV}/2016postVFP/ID/Muon"
alias skmuid_2017="cd ${SKFlat_WD}/data/${SKFlatV}/2017/ID/Muon"
alias skmuid_2018="cd ${SKFlat_WD}/data/${SKFlatV}/2018/ID/Muon"
alias skfr_2016a="cd ${SKFlat_WD}/data/${SKFlatV}/2016preVFP/FakeRate"
alias skfr_2016b="cd ${SKFlat_WD}/data/${SKFlatV}/2016postVFP/FakeRate"
alias skfr_2017="cd ${SKFlat_WD}/data/${SKFlatV}/2017/FakeRate"
alias skfr_2018="cd ${SKFlat_WD}/data/${SKFlatV}/2018/FakeRate"
alias skmva_2016a="cd ${SKFlat_WD}/data/${SKFlatV}/2016preVFP/MVAClassifier"
alias skmva_2016b="cd ${SKFlat_WD}/data/${SKFlatV}/2016postVFP/MVAClassifier"
alias skmva_2017="cd ${SKFlat_WD}/data/${SKFlatV}/2017/MVAClassifier"
alias skmva_2018="cd ${SKFlat_WD}/data/${SKFlatV}/2018/MVAClassifier"



alias sktools="cd ${SKFlat_WD}/AnalyzerTools"
alias skformat="cd ${SKFlat_WD}/DataFormats" 
alias skscript="cd ${SKFlat_WD}/script"

alias skrun="cd ${SKFlat_WD}/script/SKRun"
alias skout="cd /data6/Users/jbhyun/SKFlatAnalyzer/SKFlatOutput/${SKFlatV}"
alias sklog="cd /data6/Users/jbhyun/SKFlatAnalyzer/SKFlatRunlog"
alias skanalysis="cd ${SKFlat_WD}/Analyzers/"

alias CleanLog="cd ${SKFlatRunlogDir}; rm -rv $(date "+%Y")*; rm -rv www/SKFlatAnalyzerJobLogs/$(date "+%Y")*; cd -"
